version: '3'

services:
  web:
    build: .
    command: gunicorn camster_dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx
    volumes:
      - ./staticfiles:/app/staticfiles  # Mount the static files directory
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx configuration file
    ports:
      - "8080:8080"
    depends_on:
      - web
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: camster_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
