# Generated by Django 4.2.15 on 2024-08-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
