# Generated by Django 4.2.15 on 2024-08-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_videoclip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='named_face',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
